Script started on 2023-02-16 12:02:45-08:00
]0;jaholt@WWWSTU-P01:~/hw2[jaholt@WWWSTU-P01 hw2]$ gcc -ansi -Wall pipe.c -o pipe[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[18Pemacs pipe.cgcc -ansi -Wall pipe.c -o pipe
]0;jaholt@WWWSTU-P01:~/hw2[jaholt@WWWSTU-P01 hw2]$ gcc -ansi -Wall pipe.c -o pipe[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[18Pemacs pipe.cgcc -ansi -Wall pipe.c -o pipe[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[18Pemacs pipe.c[6P./pipe
Please enter the inner radius of the pipe (r): 5.2

Please enter the outer radius of the pipe (R): 6.2

Please enter the length of the pipe (L): 6

The thickness of the pipe is: (1.000000)
The volume of the pipe is: (214.884764)
Surface area of the inner pipe: (196.035223)
Surface area of the outer pipe: (233.734305)
Surface area of the rings: (71.628255)
The total surface area of the pipe: (501.397783)
]0;jaholt@WWWSTU-P01:~/hw2[jaholt@WWWSTU-P01 hw2]$ exit
exit

Script done on 2023-02-16 12:03:24-08:00
